### ISSUE TITLE
Simple Importer's Team Form fails when prefix is unticked

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#453] opened 2017-04-16 13:22 UTC
```
ValueError at /demo_simple/admin/import/simple/teams/
'TeamForm' has no field named 'short_reference'.
```

Not urgent, I should be able to fix it today/tomorrow

**Comment by czlee** [comment] 2017-04-19 00:35
The fix to this is nontrivial, unfortunately, sorry about the oversight. It's actually a little frustrating. The root cause is that `Team.clean()` checks that the `short_reference` field is non-empty if `use_institution_prefix` is `True` (in order to avoid teams with blank names). Every model created by this form doesn't have a `short_reference` at first, because there's no such field on the form. Ordinarily, this shouldn't be a problem: Django has a very elaborate system for dealing with `ModelForm`s that don't contain all fields of the model, which is meant to prevent things like this. This system prevents the form, for example, from complaining that `short_reference` was empty. Bur our custom check in the `Team.clean()` override still attempts to check it.

When it does so, it adds an error to the `'short_reference'` field. So far, so good—I mean, the error shouldn't be there (because it shouldn't be checking the `short_reference` field), but at least it hasn't crashed at this point. But finally, when the _form_ tries to assign this `'short_reference` error from the _model_ to a field on the _form_, it can't find a place to put it, so it crashes.

The proper fix is to exclude this check, in the same way that Django excludes validation on the `short_reference` in general. But irritatingly, it appears that Django doesn't provide a means to communicate the `exclude=` argument passed to `Model.full_clean(exclude=[])`, to `Model.clean()`. I'll need to look into this further.

If you need a workaround, just comment out lines 266-267 of participants/models.py. Needless to say, this is not a long-term solution.

**Comment by philipbelesky** [comment] 2017-04-19 06:21
Hmm, should I proceed with the front-end workaround then? It seems like any solution to the form logic itself would be a little tenuous given how resistant django is to excluding the checks. Including the field and hiding it on the front end sounds like it would be (relatively) cleaner?

**Comment by czlee** [comment] 2017-04-19 06:26
Hmm, yeah. I guess if we just add a hidden field for `short_reference`, JavaScript would then populate it just before submission? Actually we might not even need JavaScript for this, the form itself could just override the field during cleaning.

**Comment by czlee** [comment] 2017-04-19 06:29
For future reference, things I tried that I think Django doesn't allow:
- Detecting `exclude=` arguments in `Team.clean()` (there's no way to do so)
- Overriding a method of `ModelForm` to set `self.instance.short_reference` (`self.instance` is created in `Team._post_clean()`, which runs `self.instance.full_clean(exclude=exclude)` immediately after creating the instance)
- Overriding `ModelForm.save()` to set `short_reference` (`self.instance.full_clean()` is run during cleaning)

**Comment by philipbelesky** [comment] 2017-04-19 08:00
Yea, I was thinking just adding a hidden field; maybe setting a character limit on it, and having jquery copy over the values on submission. Should I go ahead with that or did you want to try the overriding-during-cleaning option?

**Comment by czlee** [comment] 2017-04-19 15:37
I'll give it a go, since about two-thirds of it would carry over into the jQuery implementation anyway. Should be able to do this this afternoon.

There's possibly a minor design question about it—overriding during cleaning doesn't allow a client to submit a different short reference at all (_e.g._ by constructing their own POST, or by disabling JavaScript and changing the hidden field value by editing the source), and it's not clear to me on the margins whether this is good or bad.

**Comment by czlee** [comment] 2017-04-20 03:12
It works! Yay! Feel free to have a look at the commit and let me know if you think jQuery would be neater.

**Closed** 2017-04-20 03:12 UTC
Labels: bug, interface-admin
