### ISSUE TITLE
Importing a tournament on a fresh instance runs into errors

### ISSUE THREAD

**Issue by amrav** [czlee/tabbycat#264] opened 2016-01-23 12:20 UTC
Hi! I'm trying to run the develop branch of Tabbycat for the IIT KGP PD. I'm running into this issue when importing a tournament on a fresh instance (I ran `pg:reset`, `makemigrations` and `createsuperuser` before this). Our tournament starts on 30 Jan, and it would be awesome if we could resolve these kind of issues before then.

Digging around the code a little, why is `get_cached_institution` useful? Isn't `self.institution` the same thing?

```
$ heroku run dj importtournament demo --slug tpd11 --name "Test PD 11" --short-name 'TPD11'
Running dj importtournament demo --slug tpd11 --name "Test PD 11" --short-name TPD11 on kgppd... up, run.6482
Importing from directory: /app/data/demo
Creating tournament 'tpd11'
Warning: Problem opening 'options': No such file or directory
Warning: Problem opening 'venue_groups': No such file or directory
Importing venues.csv
Imported 23 🎪 venues, 7 🏢 venue groups, hit 0 errors
Importing regions.csv
Imported 7 🌏 regions, hit 0 errors
Importing institutions.csv
Imported 0 🌏 regions, 13 🏫 institutions, hit 0 errors
Importing break_categories.csv
Imported 4 🎉 break categories, hit 0 errors
Warning: Problem opening 'teams': No such file or directory
Importing speakers.csv
Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/importer/management/commands/importtournament.py", line 66, in handle
    self._make('speakers')
  File "/app/importer/management/commands/importtournament.py", line 119, in _make
    counts, errors = import_method(f)
  File "/app/importer/anorak.py", line 252, in import_speakers
    counts, errors = self._import(f, _speaker_line_parser, pm.Speaker, counts=counts, errors=errors)
  File "/app/importer/base.py", line 191, in _import
    description = model.__name__ + "(" + ", ".join(["%s=%r" % args for args in kwargs.items()]) + ")"
  File "/app/importer/base.py", line 191, in <listcomp>
    description = model.__name__ + "(" + ", ".join(["%s=%r" % args for args in kwargs.items()]) + ")"
  File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/base.py", line 459, in __repr__
    u = six.text_type(self)
  File "/app/participants/models.py", line 175, in __str__
    return "[{}] {}".format(self.tournament.slug, self.short_name)
  File "/app/participants/models.py", line 186, in short_name
    return str(institution.code + " " + name)
AttributeError: 'NoneType' object has no attribute 'code'
```

**Comment by amrav** [comment] 2016-01-23 13:13
I'm using the demo folder as-is, without modifications.

I eventually went with deploying to a new Heroku instance, which worked. I assume that the cache was in some kind of inconsistent state, since I reset the database and ran `clear_cache` before importing. In general, what's the best way to reset a Heroku instance to a pristine state without destroying and recreating it?

**Comment by czlee** [comment] 2016-01-23 16:37
Did you deploy it to Heroku using the `deploy_heroku.py` script?

As far as I can tell you're doing everything right, and neither of these are issues that we've seen before. The way backups should work is exactly what you say: `pg:backups capture`, then `pg:backups restore`.

Can you describe what you're seeing in more detail, ideally so that we can try to reproduce it? I just tried starting a new Heroku instance and the importtournament command worked fine with the arguments you gave.

The only thing is that you shouldn't (in theory) need to run `makemigrations` or `createsuperuser` yourself. We've started committing migrations to the Git repo on the develop branch, (starting from version 0.8) `makemigrations` shouldn't be necessary, ever. As for `createsuperuser`, `deploy_heroku.py` is meant to do that for you. But this is unlikely to be a cause: running either command twice isn't generally harmful.

Since you're using the develop branch, I should say (if you're not already aware) that in preparation for 0.8 we've migrated our documentation to Read The Docs: http://tabbycat.readthedocs.org/. But the Heroku instructions haven't really changed, anyway.

**Comment by czlee** [comment] 2016-01-23 16:55
Actually, on clearing the cache, I'm not completely sure on how well `dj clear_cache` is working. That was sort of a stopgap we did at Korea Australs that wasn't entirely successful (we were trying to clear the cache of public pages). If you find that's clearing the cache properly, log into heroku.com, find your app, then click on the MemCachier link. It should take you to a page that looks like this:

![image](https://cloud.githubusercontent.com/assets/1725499/12531413/c9eb2136-c1ae-11e5-80d4-661c618ce547.png)

Then the "Flush Cache" button should do the trick.

Before you do this we'd still like to understand the instance in which you have to clear the cache though! In theory the only time you should have to clear the cache to get it to work is when there's a change to the database that's not showing up in the public pages (which are cached for longer periods).

**Comment by amrav** [comment] 2016-01-23 18:07
Unfortunately I've already deleted and recreated the problematic Heroku instance. However, here are the steps I followed that made the issue show up:

1. Run the `master` branch of tabbycat on Heroku by following the deploy instructions.
2. Import a tournament from `demo` into `test_pd`, run a couple of rounds.
3. `pg:reset` the database, and run `clear_cache`, `migrate` and `createsuperuser`.
4. Go to a url that should be a 404 (like `/t/test_pd`) and see a "Welcome to Test PD" message. Strange.
5. Investigate in the browser and see that it's not cached client side. Hit Ctrl-Shift-F5 to request a cache refresh server side.
6. See 404, 500 and 200 (that shouldn't exist) in no particular order or pattern each time you refresh. Stranger.
7. Restart the dyno and run `clear_cache` again. 500s and 200s seem to disappear.
8. Import tournament from `demo`. Run into issue shown above.

Proper way to reset Heroku instance (AFAIK):
1. Destroy current instance.
2. Create new instance and run `deploy_heroku.py`.

But this doesn't let me restore from a backup. I'll try clearing the cache from memcachier and tell you how that goes.

**Comment by czlee** [comment] 2016-01-23 18:29
Okay, I just tried that and at step 4 I get a 404 as expected, and when I go to the root page I get a page with no tournaments list. Sorry :confused: let us know if it happens again

**Comment by czlee** [comment] 2016-01-23 18:31
Actually, question: what are your PUBLIC_PAGE_CACHE_TIMEOUT and TAB_PAGES_CACHE_TIMEOUT settings set to, if anything? (run `heroku config`)

**Comment by amrav** [comment] 2016-01-23 18:56
Those config vars aren't set to anything.

**Comment by czlee** [comment] 2016-01-23 18:59
Okay, that's good. Cached public pages should time out after a minute then.
Admin site pages aren't cached at all though so I'm guessing this wouldn't
explain anything you're seeing.

**Comment by czlee** [comment] 2016-02-01 00:37
Did we ever see this again or did this seem to be resolved?

**Comment by philipbelesky** [comment] 2016-02-01 01:17
Yea, I wasn't able to reproduce, so I guess I'll close it as it seemed to point towards something wrong with that specific heroku instance.

**Closed by philipbelesky** 2016-02-01 01:17 UTC
Labels: ready
