### ISSUE TITLE
Investigate "Round matching query does not exist" errors

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#381] opened 2016-09-10 02:46 UTC
These still seem to keep happening. Latest batch from an instance on 1.1.1. There must be some form of weird database editing going on but it seems the front-end should catch it better.

Log for errors at `/admin/overview/`

```
DoesNotExist at /gdfgdfg/admin/overview/ Round matching query does not exist.

Request Method: GET Request URL: https://sndc.herokuapp.com/gdfgdfg/admin/overview/ Django Version: 1.10.1 Python Executable: /app/.heroku/python/bin/python Python Version: 3.5.1 Python Path: ['/app/.heroku/python/bin', ‘/app’, ‘/app/.heroku/python/lib/python35.zip’, ‘/app/.heroku/python/lib/python3.5’, ‘/app/.heroku/python/lib/python3.5/plat-linux’, ‘/app/.heroku/python/lib/python3.5/lib-dynload’, ‘/app/.heroku/python/lib/python3.5/site-packages’, ‘/app/.heroku/python/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg’, ‘/app/.heroku/python/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg’, ‘/app/.heroku/python/lib/python3.5/site-packages/newrelic-2.70.0.51’, ‘/app/tabbycat’] Server time: Thu, 8 Sep 2016 22:32:56 +1000 Installed Applications: ('jet',

'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django_gulp',
'whitenoise.runserver_nostatic',
'django.contrib.staticfiles',
'django.contrib.humanize',
'django.contrib.messages',
'actionlog',
'adjallocation',
'adjfeedback',
'availability',
'breakqual',
'divisions',
'draw',
'motions',
'options',
'participants',
'printing',
'results',
'tournaments',
'venues',
'utils',
'standings',
'importer',
'dynamic_preferences',
'django_extensions')
Installed Middleware: ['django.middleware.security.SecurityMiddleware',

'whitenoise.middleware.WhiteNoiseMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'utils.middleware.DebateMiddleware']
Traceback:

File “/app/.heroku/python/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py” in _get_

170.             rel_obj = getattr(instance, self.cache_name)

  
    During handling of the above exception ('Tournament' object has no attribute '_current_round_cache'), another exception occurred:
  
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/exception.py” in inner

39.             response = get_response(request)
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py” in _get_response

187.                 response = self.process_exception_by_middleware(e, request)
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py” in _get_response

185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File “/app/.heroku/python/lib/python3.5/site-packages/django/views/generic/base.py” in view

68.             return self.dispatch(request, *args, **kwargs)
File “/app/.heroku/python/lib/python3.5/site-packages/django/contrib/auth/mixins.py” in dispatch

56.         return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
File “/app/.heroku/python/lib/python3.5/site-packages/django/views/generic/base.py” in dispatch

88.         return handler(request, *args, **kwargs)
File “/app/tabbycat/tournaments/views.py” in get

65.         if tournament.current_round is None:
File “/app/.heroku/python/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py” in _get_

179.                 rel_obj = qs.get()
File “/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py” in get

385.                 self.model._meta.object_name
Exception Type: DoesNotExist at /gdfgdfg/admin/overview/ Exception Value: Round matching query does not exist. Request information: USER: alitaher
```

Log for errors at `https://sndc.herokuapp.com/fdsgdfgdf/admin/results/ballots_status/`:

```
DoesNotExist at /fdsgdfgdf/admin/results/ballots_status/ Round matching query does not exist.

Request Method: GET Request URL: https://sndc.herokuapp.com/fdsgdfgdf/admin/results/ballots_status/ Django Version: 1.10.1 Python Executable: /app/.heroku/python/bin/python Python Version: 3.5.1 Python Path: ['/app/.heroku/python/bin', ‘/app’, ‘/app/.heroku/python/lib/python35.zip’, ‘/app/.heroku/python/lib/python3.5’, ‘/app/.heroku/python/lib/python3.5/plat-linux’, ‘/app/.heroku/python/lib/python3.5/lib-dynload’, ‘/app/.heroku/python/lib/python3.5/site-packages’, ‘/app/.heroku/python/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg’, ‘/app/.heroku/python/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg’, ‘/app/.heroku/python/lib/python3.5/site-packages/newrelic-2.70.0.51’, ‘/app/tabbycat’] Server time: Thu, 8 Sep 2016 22:35:03 +1000 Installed Applications: ('jet',

'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django_gulp',
'whitenoise.runserver_nostatic',
'django.contrib.staticfiles',
'django.contrib.humanize',
'django.contrib.messages',
'actionlog',
'adjallocation',
'adjfeedback',
'availability',
'breakqual',
'divisions',
'draw',
'motions',
'options',
'participants',
'printing',
'results',
'tournaments',
'venues',
'utils',
'standings',
'importer',
'dynamic_preferences',
'django_extensions')
Installed Middleware: ['django.middleware.security.SecurityMiddleware',

'whitenoise.middleware.WhiteNoiseMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'utils.middleware.DebateMiddleware']
Traceback:

File “/app/.heroku/python/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py” in _get_

170.             rel_obj = getattr(instance, self.cache_name)

  
    During handling of the above exception ('Tournament' object has no attribute '_current_round_cache'), another exception occurred:
  
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/exception.py” in inner

39.             response = get_response(request)
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py” in _get_response

187.                 response = self.process_exception_by_middleware(e, request)
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py” in _get_response

185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File “/app/.heroku/python/lib/python3.5/site-packages/django/contrib/auth/decorators.py” in _wrapped_view

23.                 return view_func(request, *args, **kwargs)
File “/app/tabbycat/utils/views.py” in foo

28.         return view_fn(request, request.tournament, *args, **kwargs)
File “/app/tabbycat/results/views.py” in ballots_status

355.     ballots = list(BallotSubmission.objects.filter(debate__round=t.current_round).order_by('timestamp'))
File “/app/.heroku/python/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py” in _get_

179.                 rel_obj = qs.get()
File “/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py” in get

385.                 self.model._meta.object_name
Exception Type: DoesNotExist at /fdsgdfgdf/admin/results/ballots_status/ Exception Value: Round matching query does not exist. Request information: USER: alitaher
```

**Comment by czlee** [comment] 2016-09-10 03:11
Right... I tried a number of creative ways to reproduce it, and to my surprise, I hit one.

Here's a method that does **not** work:
 1. Open a `dj shell`.
 2. Grab a `tournament = Tournament.objects.first()`.
 3. Set `tournament.current_round_id` to some random number that is not actually a round's ID.
 4. `tournament.save()`.
This doesn't work, because the database enforces foreign key constraints, so will raise an `IntegrityError` if you try to save the tournament.

But here's how to reproduce it. Open a `dj shell`, then
**_(Warning: This deletes almost everything in the database!)_**
```
from tournaments.models import Tournament, Round
tournament = Tournament.objects.first()
fake = Round.objects.create(tournament=demo, seq=100, name="Fake round", abbreviation="Fake", draw_type='M')
tournament.current_round = fake
tournament.save()
fake.delete()
```

The last line will **delete the tournament**. But I think the tournament is still present in the cache, so the page /mytournament/admin/overview/ will still attempt to load… with this error.

Really, what _should_ happen is that if the current round is deleted, `tournament.current_round` should be set to `None`.

**Comment by czlee** [comment] 2016-09-10 03:13
On another note, if this is how the error above _actually_ happened, then that means that both of the above tournaments probably accidentally deleted their entire site… :open_mouth:

**Comment by czlee** [comment] 2016-09-10 03:20
Have confirmed that you can reproduce through editing the database in Jet:
1. Create a new round
2. Set a tournament's current round to your new round
3. Delete your new round

And commit 3f817f3 (above) doesn't help—the `tournament.current_round` still lurks around the cache somehow. I think we need to add a post-delete hook or something.

**Comment by czlee** [comment] 2016-09-10 04:37
So... this is a bit of a mission:
(The `for i in range(1)` bit is just to get it to act as a block.)

```
In [5]: for i in range(1):
   ...:     fake = Round.objects.create(tournament=demo, seq=100, name="Fake", abbreviation="Fake", draw_type='M')
   ...:     demo.current_round = Round.objects.get(seq=100)
   ...:     demo.save()
   ...:     Round.objects.get(seq=100).delete()
   ...:     
[2016-09-09 21:32:02,828] DEBUG tournaments.signals: Cleared cache demo_100_object for [Demo] Fake
[2016-09-09 21:32:02,888] DEBUG tournaments.signals: Cleared cache demo_100_object for [Demo] Fake
[2016-09-09 21:32:02,889] DEBUG tournaments.signals: Cleared demo tournament cache because the current round is [Demo] Fake

In [6]: for i in range(1):
   ...:     fake = Round.objects.create(tournament=demo, seq=100, name="Fake", abbreviation="Fake", draw_type='M')
   ...:     demo.current_round = Round.objects.get(seq=100)
   ...:     demo.save()
   ...:     Round.objects.filter(seq=100).delete()
   ...:     
[2016-09-09 21:32:13,476] DEBUG tournaments.signals: Cleared cache demo_100_object for [Demo] Fake
[2016-09-09 21:32:13,596] DEBUG tournaments.signals: Cleared cache demo_100_object for [Demo] Fake
[2016-09-09 21:32:13,596] DEBUG tournaments.signals: Cleared demo tournament cache because the current round is None

In [7]: 
```

Even after deletion, we have to cover both the cases where the tournament's current round _has_ and _hasn't_ been set to null, in the post-delete signal, since it might or might not have been depending on how the round was deleted.

Anyway, I think this should be fixed now. Maybe we need to be a bit more careful about caching?

**Closed by czlee** 2016-09-10 04:37 UTC
Labels: bug

**Comment by czlee** [comment] 2016-09-10 04:43
While I was fixing this, another thought occurred to me. Say the following happened:

1. A user created a round with seq 7
2. The user then deleted that round
3. The user then created another round with seq 7

Or even:

1. A user created a round with seq 7
2. The user then decides to insert a new round before seq 7
3. She changes that round to seq 8
4. She creates a new round with seq 7

Wouldn't this corrupt the round caches? Should cache keys for rounds be by `id` rather than by `seq`, and similarly for tournaments?

I thought at first that `post_delete` signals would help avoid this, but they would only help sidestep the first above scenario, It wouldn't do anything with the second, because nothing gets deleted. Specifically, assuming caches are cleared on `post_delete`, in the second scenario, the cache for `mytournamentslug_7_object` would still have the old round 7, now round 8, in it? Since caches are only updated in `RoundMixin.get_round()`, I think?

**Comment by philipbelesky** [comment] 2016-09-10 04:43
Yea, it might be worth testing how much performance we loose not caching `Tournament` and `Round` objects and see if it remains worth it.

**Comment by philipbelesky** [comment] 2016-09-10 04:45
(Just saw the new post) Yes, if there is going to be a caching system, it should be by a value like id that is not volatile. Should we move this to a seperate issue?

**Comment by czlee** [comment] 2016-09-10 04:46
Yeah. Also, the performance thing. That's a good point, I guess we did it before we had a good grasp of our performance bottlenecks.

**Comment by czlee** [comment] 2016-09-10 21:43
@philipbelesky FYI, I cherry-picked this on to the hotfix/v1.1.2 branch (I forgot to put it there originally). Arguably a little bit more than should be in a hotfix, since I moved all the signals to signals.py files as well.
