### ISSUE TITLE
Catch/display to user common venue auto allocation errors

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#364] opened 2016-08-11 07:24 UTC
In the venue allocator we assert the number of venues available is >= the number of debates:

```assert len(self._preferred_venues) == len(debates), "{:d} preferred venues " \
            "but {:d} debates".format(len(self._preferred_venues), len(debates))```

Ideally this problem would bounce back an error message to the user rather than throwing an exception. Ideas:

- Check that the Draw page is showing that there are too few venues for the number of debates (as it should be)
- Check the Assign Venues page is showing the same warning
- Ideally a modal error or a proper user facing error message something should be thrown if users go ahead despite these warnings, but I'm happy to kick that to #354 if the above items are done.

Related error:

```
Internal Server Error: /t/tw206/admin/venues/round/1/autoallocate/

AssertionError at /t/tw206/admin/venues/round/1/autoallocate/
11 preferred venues but 12 debates
```

**Comment by czlee** [comment] 2016-08-12 21:28
Typically this error isn't a user error in its own right, it indicates that there's a bug in the allocator code. Unfortunately stack traces don't really provide enough information to help diagnose the problem though.

I thought about it some more though, and it's possible that this could be caused by the user checking in too few venues—the allocator itself doesn't check for this possibility. During draw generation, this should be caught by the UI preventing the user from generating a draw when too few venues are checked in. However, when auto-allocate is done in the "Edit Venues" page, which was the case in this error, no such check is made. So I'll get the allocator to check this and throw an exception, caught by the view to display an error messages.

That said: In the event that there aren't enough venues, do you think that the system should (a) refuse to allocate any venues, or (b) allocate as many as it can and then alert the user about incompleteness after the fact? (In 3cad473 I've changed it to do the latter, though without an error message, which requires a non-exception-based error message paradigm.)

On another note, AssertionErrors should never happen (that's the whole point of them) but when they do happen it's probably best for them not to crash the app entirely either. There are a couple things I have in mind on this. One of them is getting the logger to e-mail admins on critical errors, so that we can generate error e-mails without causing a 500, done in 3cad473. Ideally, for complex calculations that go wrong, the resulting e-mail would also include all debug messages, to help track down how the critical message came about.

**Comment by czlee** [comment] 2016-08-12 22:27
@philipbelesky I've basically done this on the view that it should do (b), warn the user but allocate as many venues as it can, rather than refuse to allocate at all. My basis is that venues aren't really "essential" to the Tabbycat system operating, and whether it's essential to a tournament probably depends on the tournament, so user override should be permissible with warnings. Will leave open for you to review, let me know if you think it should be (a).

**Comment by philipbelesky** [comment] 2016-08-13 03:06
Doing (b) sounds good; it should be much more apparent to the user what has gone wrong when debates don't have venues allocated (and much easier to fix).

Which emails are difficult to pass into a critical email message? The kind of contextual variables and path traces that are shown in a 500 error template?

**Comment by czlee** [comment] 2016-08-13 04:34
You need more than just contextual variables to debug this kind of thing—you need all the `logger.debug()` calls output by the generator/algorithm before it crashed. I think that's a distinct issue though (so if (b) sounds good I'm closing).

**Closed by czlee** 2016-08-13 04:35 UTC
Labels: interface-admin
